services:
  - type: web
    name: fairlens-api
    env: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT app:app
    envVars:
      - key: GEMINI_API_KEY
        sync: false
